config/routes.rb
Blackjack::Application.routes.draw do
  get "/" => "static_pages#lobby", :as => "root"  
  get 'static_pages/lobby', to: 'static_pages#lobby', as: 'lobby'
  get 'static_pages/table/:game_table', to: 'static_pages#table', as: 'table'
  get 'static_pages/user_edit', to: 'static_pages#user_edit', as: 'user_edit'
  

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def lobby
  end

  def table
    @game_table = params[:game_table]
  end

  def user_edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
 %head

  %title
   Blackjack
 %body
  %aside#user-statistics-widget
   %h2 Player Statistics
   .test-name player name
   .test-avatar avatar
   .test-chip-count number of chips
   .test-level level number
   = link_to 'Edit', user_edit_path, :class => "test-edit-link"
   / %a.test-edit-link{:href => "user_edit"}Edit
  = yield

app/views/static_pages/lobby.html.haml
%h1.test-lobby-header Lobby
%p Welcome to the Blackjack Lobby!

%h3 Game Tables

%ul
 %li
  = link_to 'High Rollers Table', table_path('High Rollers Table'), :class => "test-high-rollers"
  / %a.test-high-rollers#test-high-rollers{:href => "table?gametable='High Rollers Table'"} High Rollers Table
  (Min bet = 100, Max = none)
 %li
  = link_to 'Intermediates Table', table_path('Intermediates Table'), :class => "test-intermediates"
  / %a.test-intermediates{:href => "table?gametable='Intermediates Table'"} Intermediates Table
  (Min bet = 50, Max = 100)
 %li
  = link_to 'Beginners Table', table_path('Beginners Table'), :class => "test-beginners"
  / %a.test-beginners{:href => "table?gametable='Beginners Table'"} Beginners Table
  (Min bet = 10, Max = 50)

app/views/static_pages/table.html.haml
:javascript
 function startGame()
 {
  document.getElementById("playing-area").style.visibility = "visible";
  document.getElementById("control-bar").style.visibility = "visible";
  initializeGame();
 }

= link_to 'Back to Lobby', lobby_path, :class => "test-back-to-lobby"
/%a.test-back-to-lobby{:href => "/static_pages/lobby"}Back to Lobby
%h1.test-table-header #{@game_table}
%p Ready to play Blackjack?
%button.test-play-btn{ :type => "button", :onclick => 'startGame()' } PLAY!
.test-dealer dealer
%section#playing-area.test-playing-area{:style => "visibility: hidden;"}
 %p This is the playing area
 .test-dealer-card-area Dealer's cards
 .test-player-card-area Player's cards
 .test-player-icon player icon
 .test-current-chip-count current chip count
%section#control-bar.test-control-bar{:style => "visibility: hidden;"}
 %p This is the control bar
 .test-current-bet current bet
 %button.test-hit-btn{ :type => "button", :onclick => 'hit()' } Hit
 %button.test-stand-btn{ :type => "button", :onclick => 'stand()' } Stand
 %button.test-double-down-btn{ :type => "button", :onclick => 'doubleDown()' } Double Down
%footer This is a footer

app/views/static_pages/user_edit.html.haml
%h1.test-account-header Account
%p Edit Account